#!/bin/sh
printfix() {
    cat <<"FIX"
Procedures to back up user data from the system must be established and executed. The Red Hat operating system provides utilities for automating such a process.  Commercial and open-source products are also available.Implement a process whereby user data is backed up from the system in accordance with local policies.
FIX
}

printdescription() {
    cat <<"DESCRIPTION"
Operating system backup is a critical step in maintaining data assurance and availability. User-level information is data generated by information system and/or application users. Backups shall be consistent with organizational recovery time and recovery point objectives.
DESCRIPTION
}

printseverity() {
    cat <<"SEVERITY"
medium
SEVERITY
}

printid() {
    cat <<"ID"
V-38488
ID
}

printtitle() {
    cat <<"TITLE"
The operating system must conduct backups of user-level information contained in the operating system per organization defined frequency to conduct backups consistent with recovery time and recovery point objectives.
TITLE
}

