#!/bin/sh
printdescription() {
    cat <<"DESCRIPTION"
Ensuring the "auditd" service is active ensures audit records generated by the kernel can be written to disk, or that appropriate actions will be taken if other obstacles exist.
DESCRIPTION
}

printtitle() {
    cat <<"TITLE"
The operating system must employ automated mechanisms to facilitate the monitoring and control of remote access methods.
TITLE
}

printseverity() {
    cat <<"SEVERITY"
medium
SEVERITY
}

printid() {
    cat <<"ID"
V-38631
ID
}

printfix() {
    cat <<"FIX"
The "auditd" service is an essential userspace component of the Linux Auditing System, as it is responsible for writing audit records to disk. The "auditd" service can be enabled with the following commands: # chkconfig auditd on# service auditd start
FIX
}

