#!/bin/sh
printseverity() {
    cat <<"SEVERITY"
medium
SEVERITY
}

printtitle() {
    cat <<"TITLE"
All rsyslog-generated log files must be group-owned by root.
TITLE
}

printdescription() {
    cat <<"DESCRIPTION"
The log files generated by rsyslog contain valuable information regarding system configuration, user authentication, and other such information. Log files should be protected from unauthorized access.
DESCRIPTION
}

printid() {
    cat <<"ID"
V-38519
ID
}

printfix() {
    cat <<"FIX"
The group-owner of all log files written by "rsyslog" should be root. These log files are determined by the second part of each Rule line in "/etc/rsyslog.conf" and typically all appear in "/var/log". For each log file [LOGFILE] referenced in "/etc/rsyslog.conf", run the following command to inspect the file's group owner:$ ls -l [LOGFILE]If the owner is not "root", run the following command to correct this:# chgrp root [LOGFILE]
FIX
}

