#!/bin/sh

option="$1"
acceptable="$2"

if grep -F "$option" /etc/audit/auditd.conf | sed 's/^[^=]*=//' | grep -qviE "$acceptable"; then
    echo "/etc/audit/auditd.conf does not have $option matching $acceptable"
    exit 1
fi

exit 0
