#!/bin/sh

file="$1"
wantedmode=0"$2"

mode=0"$(stat -c %a "$file")"

# if mode has more unspecified bits that aren't in perms
if [ "$((($mode | $wantedmode) != $wantedmode))" -ne 0 ]; then
    echo "$file permissions ($mode) are too permissive"
    exit 1
fi

exit 0
