#!/bin/sh
printid() {
    cat <<"ID"
V-38628
ID
}

printfix() {
    cat <<"FIX"
The "auditd" service is an essential userspace component of the Linux Auditing System, as it is responsible for writing audit records to disk. The "auditd" service can be enabled with the following commands: # chkconfig auditd on# service auditd start
FIX
}

printtitle() {
    cat <<"TITLE"
The operating system must produce audit records containing sufficient information to establish the identity of any user/subject associated with the event.
TITLE
}

printdescription() {
    cat <<"DESCRIPTION"
Ensuring the "auditd" service is active ensures audit records generated by the kernel can be written to disk, or that appropriate actions will be taken if other obstacles exist.
DESCRIPTION
}

printseverity() {
    cat <<"SEVERITY"
medium
SEVERITY
}

